# Generated by Django 3.2.20 on 2023-08-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User role'), ('admin', 'Administrator role')], default='user', max_length=15),
        ),
    ]
